### ISSUE TITLE
Getting Deadlock from Subclipse

### ISSUE THREAD

**Issue by lidochca** [subclipse/subclipse#122]
Hello Mark Phippard, all,

Thank you Mark for your hard work, for you plugins.
We are using it and unfortunately having following problem:

When I am opening my projects, many thinks happens in background at open and sometimes I am getting following deadlock from subclipse, when it tries to associate current project to SVN.

Can we reduce the stress by deferring auto connect, auto association to SVN ? 

`ENTRY org.eclipse.core.jobs 4 2 2020-01-15 15:49:22.574`
`!MESSAGE Deadlock detected. All locks owned by thread main will be suspended.`
`!STACK 0`
`java.lang.IllegalStateException
	at org.eclipse.core.internal.jobs.DeadlockDetector.reportDeadlock(DeadlockDetector.java:599)
	at org.eclipse.core.internal.jobs.DeadlockDetector.lockWaitStart(DeadlockDetector.java:403)
	at org.eclipse.core.internal.jobs.LockManager.addLockWaitThread(LockManager.java:154)
	at org.eclipse.core.internal.jobs.OrderedLock.doAcquire(OrderedLock.java:168)
	at org.eclipse.core.internal.jobs.OrderedLock.acquire(OrderedLock.java:106)
	at org.eclipse.core.internal.jobs.OrderedLock.acquire(OrderedLock.java:82)
	at org.eclipse.cdt.internal.core.settings.model.xml.XmlProjectDescriptionStorage.getProjectDescription(XmlProjectDescriptionStorage.java:230)
	at org.eclipse.cdt.internal.core.settings.model.CProjectDescriptionManager.getProjectDescriptionInternal(CProjectDescriptionManager.java:426)
	at org.eclipse.cdt.internal.core.settings.model.CProjectDescriptionManager.getProjectDescription(CProjectDescriptionManager.java:408)
	at org.eclipse.cdt.managedbuilder.core.ManagedBuildManager.findBuildInfo(ManagedBuildManager.java:2730)
	at org.eclipse.cdt.managedbuilder.core.ManagedBuildManager.getBuildInfo(ManagedBuildManager.java:2991)
	at org.eclipse.cdt.managedbuilder.core.ManagedBuildManager.getBuildInfo(ManagedBuildManager.java:2946)
	at org.eclipse.cdt.managedbuilder.core.ResourceChangeHandler2$Visitor.visit(ResourceChangeHandler2.java:123)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:64)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:75)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:48)
	at org.eclipse.cdt.managedbuilder.core.ResourceChangeHandler2.resourceChanged(ResourceChangeHandler2.java:180)
	at org.eclipse.core.internal.events.NotificationManager$1.run(NotificationManager.java:299)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.NotificationManager.notify(NotificationManager.java:289)
	at org.eclipse.core.internal.events.NotificationManager.broadcastChanges(NotificationManager.java:152)
	at org.eclipse.core.internal.resources.Workspace.broadcastPostChange(Workspace.java:374)
	at org.eclipse.core.internal.resources.Workspace.endOperation(Workspace.java:1469)
	at org.eclipse.core.internal.resources.Project.touch(Project.java:1326)
	at org.eclipse.team.core.RepositoryProvider.map(RepositoryProvider.java:132)
	at org.tigris.subversion.subclipse.core.resources.SVNWorkspaceRoot.setSharing(SVNWorkspaceRoot.java:229)
	at org.tigris.subversion.subclipse.core.SVNTeamProviderType$AutoShareJob.autoconnectSVNProject(SVNTeamProviderType.java:136)
	at org.tigris.subversion.subclipse.core.SVNTeamProviderType$AutoShareJob.run(SVNTeamProviderType.java:98)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)`
`!SUBENTRY 1 org.eclipse.core.jobs 4 2 2020-01-15 15:49:22.574
!MESSAGE Thread Worker-12 has locks: F/MyCDTProject/.settings, R/, OrderedLock (5), OrderedLock (0) and is waiting for lock OrderedLock (16)`
`!SUBENTRY 1 org.eclipse.core.jobs 4 2 2020-01-15 15:49:22.574`
`!MESSAGE Thread main has locks: OrderedLock (16) and is waiting for lock F/MyCDTProject/.settings
`

I am looking for a quick solution to postpone association and to make a patch for my working eclipse. Could you please point me where could be the best place to do it?

Thank you
Kind Regards
Lidia

**Comment by markphip** [comment]
> 
> I am looking for a quick solution to postpone association and to make a patch for my working eclipse. Could you please point me where could be the best place to do it?

I am not really sure what you are asking.  The code for this project is here mostly in the bundles folder. Probably everything relevant here would be in the core bundle.

**Comment by lidochca** [comment]
I was trying to pospone the auto associate to SVN.
I tried 
org.tigris.subversion.subclipse.core.SVNTeamProviderType class
`getAutoShareJob() method {
.....
	autoShareJob.schedule(30000);
...
}`
But it is not helping, seems that `autoShareJob` is executed only when it couldn't associate from the beginning and the list `projectsToShare` is not empty. 

basically, 
The deadlock happens only for this cases, when it tries again to associate left open projects. 
and  when `autoShareJob.schedule();` is executed.

Thank you
Lidia

**Comment by lidochca** [comment]
Hi Mark ,
Eventually it could happen that the root cause of deadlock I am having comes from CDT plugin.  
I will do more investigation and will let you know if here is a problem with subclipse.
Thanks
Lidia

**Comment by lidochca** [comment]
I will close this issue as the subclipse plugins are not the root cause of deadlock in my case.
