### ISSUE TITLE
NullPointerException at org.tigris.subversion.subclipse.ui.internal.TeamAction.selectionChanged(TeamAction.java:256)

### ISSUE THREAD

**Issue by el-teedee** [subclipse/subclipse#126]
I have exactly the same bug than in (apparently fixed in Eclipse 4.3) this bug : #103 which also looks like related to #77

I can't write steps to reproduce, since the bug is random, or more likely a consequence of some actions related with SVN, like opening a file linked to SVN, then close the editor, then swith to another file editor.

My only workaround is to restart Eclipse to get rid of it.

Error log:

```
java.lang.NullPointerException
	at org.tigris.subversion.subclipse.ui.internal.TeamAction.selectionChanged(TeamAction.java:256)
	at org.tigris.subversion.subclipse.ui.actions.ConfigurableMergeAction.selectionChanged(ConfigurableMergeAction.java:23)
	at org.eclipse.ui.internal.PluginAction.refreshEnablement(PluginAction.java:201)
	at org.eclipse.ui.internal.PluginAction.selectionChanged(PluginAction.java:264)
	at org.eclipse.ui.internal.PluginAction.selectionChanged(PluginAction.java:288)
	at org.eclipse.ui.internal.e4.compatibility.SelectionService.notifyListeners(SelectionService.java:240)
[...]
	at org.eclipse.equinox.launcher.Main.main(Main.java:1438)
```

Note that the stacktraces looks quite the same than in #103 , only differing on line numbers.

My components version (Eclipse Web Developpers Tools): 
```
Eclipse Version: 2019-12 (4.14.0) / Build id: 20191212-1212

Eclipse.org	Eclipse Platform	        4.14.0.v20191210-0610	org.eclipse.platform
Eclipse.org	Eclipse Java Development Tools	3.18.200.v20191210-0610	org.eclipse.jdt
tigris.org	Subversion Client Adapter	1.10.3	org.tigris.subversion.clientadapter.feature
tigris.org	Subversion JavaHL	        1.8.15	org.tigris.subversion.clientadapter.javahl.feature
tigris.org	SVN Team Provider Core	        1.10.13	org.tigris.subversion.subclipse
tigris.org	SVNKit Client Adapter	        1.8.9	org.tigris.subversion.clientadapter.svnkit.feature

```

**Comment by t106uhn** [comment]
I've have the same issue too and it's very annoying. Luckily most of my projects are in Git. I'm gonna close my SVN projects and close the SVN perspective while i work of the code in my Git projects/repos.

**Comment by selsemore** [comment]
The error log shown above would seem to come from a Subclipse version that does not include the fix for #103 and #77. Since that fix, TeamAction.java:256 has not been a statement that could possibly result in a NPE.

**Comment by t14z** [comment]
你好！你的邮件已收到
