### ISSUE TITLE
Show Annotation problems

### ISSUE THREAD

**Issue by LaurentBarbareau** [subclipse/subclipse#139]
Hi,

Show Annotation function is not working properly for every type of files.

I have no problem with Java files. This is often not the case with XML or other types of files (JSP, text...).

First, when I use my user shortcut (CTRL + ALT + A), it displays the Show Annotation window, I click Ok and nothing happens.
By the way I can see the command into the SVN console, as:
blame -r 1:HEAD C:/dev/wwwwwwww.xml@1201
I also got the following error into the Error view:
```
java.lang.NullPointerException
	at org.tigris.subversion.subclipse.ui.operations.ShowAnnotationOperation.getEditor(ShowAnnotationOperation.java:228)
	at org.tigris.subversion.subclipse.ui.operations.ShowAnnotationOperation.access$0(ShowAnnotationOperation.java:210)
	at org.tigris.subversion.subclipse.ui.operations.ShowAnnotationOperation$1.run(ShowAnnotationOperation.java:156)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4005)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3633)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1158)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1047)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:658)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:557)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:154)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:150)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1447)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1420)
```

Secondly, if I use the right click menu > Team > Show Annotation... the problem is different, it opens a new basic text editor and I can see annotations. Not very practical...

It's like that at least since Eclipse 2019-12 and now I'm using 2020-06. Previously I don't know I was using Subversive under Eclipse Mars and there was no pb of that kind.

**Comment by selsemore** [comment]
I haven't reproduced this problem, but from the stack trace I can see that it is happening while checking to see if there is already an open editor for the resource that supports annotations so that the annotations can be applied there. I imagine that it is a problem similar to the one fixed for Issue #77.  I'm going to make a change to null proof  that method. Regarding the second issue about the right click menu action opening a new basic text editor, this would be the expected behavior if the default editor associated with the file type does not support quick diff annotations (meaning it does not implement the ITextEditorExtension4 interface). For example, the multipage XML editor does not.
