### ISSUE TITLE
module java.base does not "opens java.lang" to unnamed module

### ISSUE THREAD

**Issue by Wouter1** [subclipse/subclipse#206]
subclipse is constantly raising errors like this
```
java.lang.reflect.InaccessibleObjectException: Unable to make field private java.lang.Throwable java.lang.Throwable.cause accessible: module java.base does not "opens java.lang" to unnamed module @38fb6e50
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:177)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:171)
	at org.tmatesoft.svn.core.javahl17.SVNClientImpl.getClientException(SVNClientImpl.java:1543)
	at org.tmatesoft.svn.core.javahl17.SVNClientImpl.status(SVNClientImpl.java:164)
	at org.tmatesoft.svn.core.javahl17.SVNClientImpl.status(SVNClientImpl.java:136)
	at org.tigris.subversion.svnclientadapter.javahl.AbstractJhlClientAdapter.getStatus(AbstractJhlClientAdapter.java:584)
	at org.tigris.subversion.svnclientadapter.javahl.AbstractJhlClientAdapter.getStatus(AbstractJhlClientAdapter.java:564)
	at org.tigris.subversion.svnclientadapter.javahl.AbstractJhlClientAdapter.getStatus(AbstractJhlClientAdapter.java:557)
	at org.tigris.subversion.svnclientadapter.svnkit.SvnKitClientAdapter.getStatus(SvnKitClientAdapter.java:107)
	at org.tigris.subversion.svnclientadapter.javahl.AbstractJhlClientAdapter.getStatus(AbstractJhlClientAdapter.java:550)
	at org.tigris.subversion.svnclientadapter.javahl.AbstractJhlClientAdapter.getStatus(AbstractJhlClientAdapter.java:543)
	at org.tigris.subversion.subclipse.core.status.RecursiveStatusUpdateStrategy.statusesToUpdate(RecursiveStatusUpdateStrategy.java:61)
	at org.tigris.subversion.subclipse.core.status.RecursiveStatusUpdateStrategy.statusesToUpdate(RecursiveStatusUpdateStrategy.java:44)
	at org.tigris.subversion.subclipse.core.status.RecursiveStatusUpdateStrategy.statusesToUpdate(RecursiveStatusUpdateStrategy.java:44)
	at org.tigris.subversion.subclipse.core.status.RecursiveStatusUpdateStrategy.statusesToUpdate(RecursiveStatusUpdateStrategy.java:44)
	at org.tigris.subversion.subclipse.core.status.RecursiveStatusUpdateStrategy.statusesToUpdate(RecursiveStatusUpdateStrategy.java:44)
	at org.tigris.subversion.subclipse.core.status.StatusCacheManager.refreshStatus(StatusCacheManager.java:301)
	at org.tigris.subversion.subclipse.core.resourcesListeners.FileModificationManager.refreshStatusInfinite(FileModificationManager.java:242)
	at org.tigris.subversion.subclipse.core.resourcesListeners.FileModificationManager.refreshStatus(FileModificationManager.java:277)
	at org.tigris.subversion.subclipse.core.resourcesListeners.FileModificationManager.access$2(FileModificationManager.java:256)
	at org.tigris.subversion.subclipse.core.resourcesListeners.FileModificationManager$2.run(FileModificationManager.java:210)
	at org.tigris.subversion.subclipse.core.util.JobUtility$1$1.run(JobUtility.java:29)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2313)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2338)
	at org.tigris.subversion.subclipse.core.util.JobUtility$1.run(JobUtility.java:26)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

since I upgraded Eclipse to Version: 2021-09 (4.21.0) Build id: 20210910-1417

I suppose this is because the java version included is more restrictive than the java version in my previous eclipse (2019-something). 

I underxtand that more and more of Eclipse is moving upward in java version 
Moving to older java (which might fix the issue but break other parts of Eclipse) so seems not a good idea.

**Comment by Wouter1** [comment]
Would it help if I uninstall the javahl library from subclipse? It seems not working properly anyway

**Comment by Wouter1** [comment]
I uninstalled javahl and restarted Eclipse. But the exact error as above persists. So, javaHL is still in the stacktrace.

**Comment by markphip** [comment]
Your problem is in SVNKit. It implements the JavaHL Java interface which is why you see that in the stack trace.

You can try reporting the problem but they have not been very responsive the last several years. I would suggest doing what is necessary so that you can switch to using JavaHL. There is info in the wiki for different OS.

**Comment by Wouter1** [comment]
@markphip  Thanks for the quick response.

But I have no idea what you are asking of me. I was already glad I could find where I can report the issue.  I have no idea what JavaHL is and who "they" are and why you need them/it. And even less what I would do to get something fixed deep in your code that apparently needs it. 

I am just hoping you can escalate the issue to the right level .

**Comment by markphip** [comment]
None of these products, including this one, have been actively developed for years. There is no one to escalate to.

The wiki attempts to explain it:

https://github.com/subclipse/subclipse/wiki#javahl-installation

Subclipse needs a SVN API. We do not provide it. JavaHL is the API provided by SVN itself. We have written Subclipse to use this API. SVNKit is a pure Java implementation of SVN by a 3rd party. Since they implemented the JavaHL interfaces it can be dropped in and also used. But we write and test Subclipse against JavaHL ... at least back in the 2000's when any of this was being actively developed.

**Comment by markphip** [comment]
I meant to add that SVNKit is a company: https://svnkit.com

They used to be responsive to problems but I would guess they are focused on other things now.

**Comment by Wouter1** [comment]
@markphip 

>Subclipse needs a SVN API. ...

If I  understand you correctly, you are depending of a piece of broken and not-anymore-supported software ?

Does it mean subclipse is unrepairably broken?

As a suggestion, Can you replace that dependency with the public SVN code? It's on https://subversion.apache.org/source-code.html

Or alternatively, should I switch from subclipse to some other eclipse SVN plugin? Any advice?

**Comment by markphip** [comment]
We depend on JavaHL .. it is part of SVN and fully supported. You are the one that is using SVNKit.

I have no idea if it is supported or even broken. There are several hundred thousand active Subclipse installations and a good number of them use SVNKit. I have no idea what the root cause of your problem is.

Subclipse is not actively maintained but it is open source and nothing is preventing you or anyone else from fixing problems that are discovered.

**Comment by Wouter1** [comment]
@markphip 
The error message originally was with JavaHL turned ON. So the initial stacktrace is for JavaHL.  I disabled it only to see if that would help fixing the issue (but it doesn't, the stacktrace remains even with javaHL disabled).

But FAIK, JavaHL has always been broken. Check eg https://stackoverflow.com/questions/11769989/failed-to-load-javahl-library which is a ticket from 10 years ago. 

I need SVN for work as a tool, I'm not expected to work on SVN.

**Comment by markphip** [comment]
I have explained all of these already. You have never been using JavaHL. Your stack trace is for SVNKit. SVNKit implements the JavaHL interfaces so you will still see JavaHL classes referenced.

JavaHL works fine. It does not mean on some OS there is not work to do to get the native libraries load. I linked you to our wiki which offers help getting it setup. You have yet to post a single reply that has acknowledged any of the answers I have given you. Good luck

**Comment by Wouter1** [comment]
@markphip 

Just to clarify.

If I see this in a stacktrace ```	at  org.tigris.subversion.svnclientadapter.javahl.AbstractJhlClientAdapter.getStatus(AbstractJhlClientAdapter.java:557)``` I assume it's javahl.  Sorry if that assumption was wrong.

Also, if I ask at installation of subclipse to install javaHL I suppose it installs JavaHL.  Do you think most users will read your wiki? I see now but did not realize that special manual  steps are needed for subclipse plugin. This is highly unusual for Eclipse plugins.

**Comment by markphip** [comment]
Yes, the assumption is wrong.

The stack trace also includes this .. which is the SVNKit classes that implement the JavaHL interfaces:

```
	at org.tmatesoft.svn.core.javahl17.SVNClientImpl.getClientException(SVNClientImpl.java:1543)
	at org.tmatesoft.svn.core.javahl17.SVNClientImpl.status(SVNClientImpl.java:164)
	at org.tmatesoft.svn.core.javahl17.SVNClientImpl.status(SVNClientImpl.java:136)
	at org.tigris.subversion.svnclientadapter.javahl.AbstractJhlClientAdapter.getStatus(AbstractJhlClientAdapter.java:584)
```

As for installing JavaHL ... yes it uses the native SVN libraries which have to be installed. Due to how libraries are loaded on different OS, Windows is the only where we are able to provide them. On MacOS and Linux, they have to be installed into the system.

Subclipse is roughly 18 years old. It has always been this way.

On MacOS, I use Homebrew but MacPorts also works well. I recently updated Homebrew's Subversion package to support Apple Silicon and Subclipse and JavaHL all work fine on that version (and of course Intel as well).

**Comment by xourge** [comment]
I managed to fix this issue on ubuntu 22. Here are the steps:

1. In console: sudo apt-get install libsvn-java
2. In eclipse: install Subversion 1.14 JavaHL. After this close eclipse.
3. In eclipse.ini: add at the end the location of the jni library: -Djava.library.path=/usr/lib/x86_64-linux-gnu/jni
4. Open eclipse and in preferences: SVN: SVN Interface: Cliente: JavaHL. Apply and close

Don't know if the 2 first steps were necessary but I put them here just in case
