### ISSUE TITLE
When running "Team->Refresh/Cleanup" in Eclipse, receive org.apache.subversion.javahl.ClientException: svn: E155004: There are unfinished work items; run 'svn cleanup' first.

### ISSUE THREAD

**Issue by wodencafe** [subclipse/subclipse#21]
I am trying to run a SVN Cleanup on my project, from the Eclipse Team -> Refresh/Cleanup option.

This happens sometimes after I have switched between a project branch and trunk, and files get conflicted to the point that Eclipse wants me to run a svn cleanup.

Well after trying to use that option in the GUI, I receive an error stating: org.apache.subversion.javahl.ClientException: svn: E155004: There are unfinished work items in '/path/to/project'; run 'svn cleanup' first."

So it's telling me I can't run cleanup because I need to run cleanup.

![screen23](https://cloud.githubusercontent.com/assets/9727493/22795884/e3660b2a-eebd-11e6-9492-4303f1c1ab51.png)

Running svn cleanup from the command line seems to solve the problem, but I should be able to do this from the GUI.

**Comment by markphip** [comment]
We do not have any code that directly does anything.  We provide a UI on top of the SVN API and it does all the work.  So our Cleanup menu action just runs the SVN cleanup API.  I do not know why it would behave differently than the command line as the CLI is just a UI in front of the same API.  I guess an exception would be if you are using SVNKit in Subclipse as opposed to JavaHL.  The latter is the same API as the command line where as the former is a reverse-engineeed pure Java implementation and perhaps it lacks something here.  Either way, all we do is call the API we do not provide it.

The only other thing I could think of is if we call some other API like status or info before we call cleanup and that API fails because of the need for cleanup.  If so, then we could fix that but from my quick look at the code I am not seeing where we do anything like that.  It looks like we dive straight into calling the cleanup API.

**Comment by wodencafe** [comment]
Hi @markphip  thanks for taking the time to look at this.

This may be more helpful, here is the stacktrace of the error from my eclipse .log file:
```

!ENTRY org.tigris.subversion.subclipse.core 4 -6 2017-02-09 11:40:42.238
!MESSAGE org.apache.subversion.javahl.ClientException: svn: E155004: There are unfinished work items in '/home/cboyd/workspace6/DXOP_5.2'; run 'svn cleanup' first.
!STACK 0
org.tigris.subversion.svnclientadapter.SVNClientException: org.apache.subversion.javahl.ClientException: svn: E155004: There are unfinished work items in '/home/cboyd/workspace6/DXOP_5.2'; run 'svn cleanup' first.
	at org.tigris.subversion.svnclientadapter.javahl.AbstractJhlClientAdapter.cleanup(AbstractJhlClientAdapter.java:2243)
	at org.tigris.subversion.subclipse.core.commands.CleanupResourcesCommand.run(CleanupResourcesCommand.java:52)
	at org.tigris.subversion.subclipse.ui.operations.CleanupOperation.execute(CleanupOperation.java:49)
	at org.tigris.subversion.subclipse.ui.operations.RepositoryProviderOperation.execute(RepositoryProviderOperation.java:74)
	at org.tigris.subversion.subclipse.ui.operations.SVNOperation.run(SVNOperation.java:90)
	at org.eclipse.team.internal.ui.actions.JobRunnableContext.run(JobRunnableContext.java:151)
	at org.eclipse.team.internal.ui.actions.JobRunnableContext$ResourceJob.runInWorkspace(JobRunnableContext.java:76)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:39)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: org.apache.subversion.javahl.ClientException: svn: E155004: There are unfinished work items in '/home/cboyd/workspace6/DXOP_5.2'; run 'svn cleanup' first.
	at org.apache.subversion.javahl.ClientException.fromException(ClientException.java:68)
	at org.tmatesoft.svn.core.javahl17.SVNClientImpl.getClientException(SVNClientImpl.java:1492)
	at org.tmatesoft.svn.core.javahl17.SVNClientImpl.cleanup(SVNClientImpl.java:616)
	at org.tigris.subversion.svnclientadapter.javahl.AbstractJhlClientAdapter.cleanup(AbstractJhlClientAdapter.java:2240)
	... 8 more
Caused by: org.tmatesoft.svn.core.SVNException: svn: E155004: There are unfinished work items in '/home/cboyd/workspace6/DXOP_5.2'; run 'svn cleanup' first.
	at org.tmatesoft.svn.core.internal.wc.SVNErrorManager.error(SVNErrorManager.java:64)
	at org.tmatesoft.svn.core.internal.wc.SVNErrorManager.error(SVNErrorManager.java:51)
	at org.tmatesoft.svn.core.internal.wc17.db.SVNWCDb.obtainWCLock(SVNWCDb.java:5655)
	at org.tmatesoft.svn.core.internal.wc2.ng.SvnNgCleanup.cleanupInternal(SvnNgCleanup.java:114)
	at org.tmatesoft.svn.core.internal.wc2.ng.SvnNgCleanup.cleanup(SvnNgCleanup.java:86)
	at org.tmatesoft.svn.core.internal.wc2.ng.SvnNgCleanup.doCleanup(SvnNgCleanup.java:53)
	at org.tmatesoft.svn.core.internal.wc2.ng.SvnNgCleanup.run(SvnNgCleanup.java:48)
	at org.tmatesoft.svn.core.internal.wc2.ng.SvnNgCleanup.run(SvnNgCleanup.java:28)
	at org.tmatesoft.svn.core.internal.wc2.ng.SvnNgOperationRunner.run(SvnNgOperationRunner.java:20)
	at org.tmatesoft.svn.core.internal.wc2.SvnOperationRunner.run(SvnOperationRunner.java:21)
	at org.tmatesoft.svn.core.wc2.SvnOperationFactory.run(SvnOperationFactory.java:1235)
	at org.tmatesoft.svn.core.wc2.SvnOperation.run(SvnOperation.java:294)
	at org.tmatesoft.svn.core.javahl17.SVNClientImpl.cleanup(SVNClientImpl.java:614)
	... 9 more
```

**Comment by markphip** [comment]
That is more helpful.  It shows you are using SVNKit so that is likely why you see different behavior.  You can check their issue tracker or report to them here:  https://svnkit.com/support.html

Or switch to using JavaHL which should always behave the same as the command line.

**Comment by wodencafe** [comment]
Thank you @markphip for the info! I will close the issue here and report it to them.

**Comment by markphip** [comment]
OK, if you keep using SVNKit and run into the problem again, before you fix it using command line see if you can switch to using JavaHL and whether that makes a difference.  That will help confirm problem.  Of course the problem here is also that it is pretty hard to setup the problem scenario in the first place so you might not run into it again anyway.

**Comment by wodencafe** [comment]
Hi again @markphip, I had to do a little extra work to enable JavaHL on Ubuntu, but it is running now and this addressed the issue.

Lucky for me the issue is easily reproducible if I  switch back to SVNKit. It is somehow caused by switching my project between a branch and the Trunk.

After changing the SVN implementation to JavaHL and trying the Refresh / Clean, it worked successfully.

However, once I tried to switch the branch back to the trunk, I received another error (maybe this should be in a different issue?)
```

org.xml.sax.SAXParseException; lineNumber: 24; columnNumber: 2; The content of elements must consist of well-formed character data or markup.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:400)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
	at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1465)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.startOfMarkup(XMLDocumentFragmentScannerImpl.java:2631)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2729)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:118)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:504)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:327)
	at org.eclipse.core.internal.resources.ProjectDescriptionReader.read(ProjectDescriptionReader.java:926)
	at org.eclipse.core.internal.localstore.FileSystemResourceManager.read(FileSystemResourceManager.java:896)
	at org.eclipse.core.internal.resources.Project.updateDescription(Project.java:1328)
	at org.eclipse.core.internal.resources.File.updateMetadataFiles(File.java:379)
	at org.eclipse.core.internal.localstore.RefreshLocalVisitor.visit(RefreshLocalVisitor.java:303)
	at org.eclipse.core.internal.localstore.UnifiedTree.accept(UnifiedTree.java:111)
	at org.eclipse.core.internal.localstore.FileSystemResourceManager.refreshResource(FileSystemResourceManager.java:974)
	at org.eclipse.core.internal.localstore.FileSystemResourceManager.refresh(FileSystemResourceManager.java:960)
	at org.eclipse.core.internal.resources.Resource.refreshLocal(Resource.java:1594)
	at org.tigris.subversion.subclipse.core.client.OperationManager.endOperation(OperationManager.java:136)
	at org.tigris.subversion.subclipse.core.client.OperationManager.endOperation(OperationManager.java:102)
	at org.tigris.subversion.subclipse.core.commands.SwitchToUrlCommand.run(SwitchToUrlCommand.java:103)
	at org.tigris.subversion.subclipse.ui.operations.SwitchOperation.execute(SwitchOperation.java:82)
	at org.tigris.subversion.subclipse.ui.operations.RepositoryProviderOperation.execute(RepositoryProviderOperation.java:74)
	at org.tigris.subversion.subclipse.ui.operations.SVNOperation.run(SVNOperation.java:90)
	at org.eclipse.team.internal.ui.actions.JobRunnableContext.run(JobRunnableContext.java:151)
	at org.eclipse.team.internal.ui.actions.JobRunnableContext$ResourceJob.runInWorkspace(JobRunnableContext.java:76)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:39)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
!SUBENTRY 1 org.eclipse.core.resources 2 567 2017-02-09 16:01:39.382
!MESSAGE Could not read metadata for 'DXOP_5.2'.
!STACK 0
org.xml.sax.SAXParseException; lineNumber: 24; columnNumber: 2; The content of elements must consist of well-formed character data or markup.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:400)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
	at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1465)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.startOfMarkup(XMLDocumentFragmentScannerImpl.java:2631)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2729)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:118)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:504)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:327)
	at org.eclipse.core.internal.resources.ProjectDescriptionReader.read(ProjectDescriptionReader.java:926)
	at org.eclipse.core.internal.localstore.FileSystemResourceManager.read(FileSystemResourceManager.java:896)
	at org.eclipse.core.internal.resources.Project.updateDescription(Project.java:1328)
	at org.eclipse.core.internal.resources.File.updateMetadataFiles(File.java:379)
	at org.eclipse.core.internal.localstore.RefreshLocalVisitor.visit(RefreshLocalVisitor.java:303)
	at org.eclipse.core.internal.localstore.UnifiedTree.accept(UnifiedTree.java:111)
	at org.eclipse.core.internal.localstore.FileSystemResourceManager.refreshResource(FileSystemResourceManager.java:974)
	at org.eclipse.core.internal.localstore.FileSystemResourceManager.refresh(FileSystemResourceManager.java:960)
	at org.eclipse.core.internal.resources.Resource.refreshLocal(Resource.java:1594)
	at org.tigris.subversion.subclipse.core.client.OperationManager.endOperation(OperationManager.java:136)
	at org.tigris.subversion.subclipse.core.client.OperationManager.endOperation(OperationManager.java:102)
	at org.tigris.subversion.subclipse.core.commands.SwitchToUrlCommand.run(SwitchToUrlCommand.java:103)
	at org.tigris.subversion.subclipse.ui.operations.SwitchOperation.execute(SwitchOperation.java:82)
	at org.tigris.subversion.subclipse.ui.operations.RepositoryProviderOperation.execute(RepositoryProviderOperation.java:74)
	at org.tigris.subversion.subclipse.ui.operations.SVNOperation.run(SVNOperation.java:90)
	at org.eclipse.team.internal.ui.actions.JobRunnableContext.run(JobRunnableContext.java:151)
	at org.eclipse.team.internal.ui.actions.JobRunnableContext$ResourceJob.runInWorkspace(JobRunnableContext.java:76)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:39)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

**Comment by markphip** [comment]
That looks like an internal Eclipse issue. Maybe search their bugzilla to see if it is known?

**Comment by wodencafe** [comment]
Will do, thank you sir :+1:

**Comment by anstnsp** [comment]
yet.... i don't know why there are unfinished work items in " ..../.../"run 'svn cleanup' first. 
T_T
