### ISSUE TITLE
svn: E204899: Cannot create new file 'XXXX.java.tmp': Zugriff verweigert

### ISSUE THREAD

**Issue by AlBundy33** [subclipse/subclipse#26]
After Installing a fresh eclipse neon on my windows 10 machine and installing subclipse from marketplace all works fine except the quick diff (compare with latest from repository)
According to older bugs I think creating patches won't work too.

The error message is
svn: E204899: Cannot create new file 'XXXX.java.tmp': Zugriff verweigert

I've installed eclipse in C:\Program Files and starting it over a windows shortcut (working dir: C:\Program Files\eclipse)

After changing the permissions on the eclipse folder (full access for my user) quick diff works without the exception.

So it seems that the diffs are creating temp-files in the current working directory - maybe it would be better to create temp-files in the temp-directory to avoid such issues.

**Comment by markphip** [comment]
We do not generally create or edit your files from our code.  We call API provided by SVN which does this. As you can see this carries an SVN error code as well which further indicates it is SVN that is creating this temp file.  I will leave this open, but AFAIK, there is nothing we could do to control this behavior via the API we call.

**Comment by AlBundy33** [comment]
So this seems to be a svnkit bug?

**Comment by markphip** [comment]
It could be an SVNKit bug.  Would be easiest if you changed to JavaHL and see if you get the problem or not.  Since you are on Windows this should be easy to try.

**Comment by AlBundy33** [comment]
Since we are using ssh+svn I haven't setup JavaHL.

**Comment by AlBundy33** [comment]
I've found a stacktrace in the eclise log - maybe this helps. ;-)

Stacktrace shows org.apache.subversion.javahl.ClientException but as mentioned I'v set my Client to SVNKit.

```
!ENTRY org.tigris.subversion.subclipse.core 4 -6 2017-03-21 17:49:12.944
!MESSAGE org.apache.subversion.javahl.ClientException: svn: E204899: Cannot create new file 'TableNameMapping.java.tmp': Zugriff verweigert
!STACK 0
org.tigris.subversion.svnclientadapter.SVNClientException: org.apache.subversion.javahl.ClientException: svn: E204899: Cannot create new file 'TableNameMapping.java.tmp': Zugriff verweigert
	at org.tigris.subversion.svnclientadapter.javahl.AbstractJhlClientAdapter.diff(AbstractJhlClientAdapter.java:2709)
	at org.tigris.subversion.subclipse.ui.operations.ShowDifferencesAsUnifiedDiffOperationWC.execute(ShowDifferencesAsUnifiedDiffOperationWC.java:50)
	at org.tigris.subversion.subclipse.ui.operations.SVNOperation.run(SVNOperation.java:90)
	at org.eclipse.team.internal.ui.actions.ProgressDialogRunnableContext$2$1.run(ProgressDialogRunnableContext.java:104)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2240)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2267)
	at org.eclipse.team.internal.ui.actions.ProgressDialogRunnableContext$2.run(ProgressDialogRunnableContext.java:100)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)
Caused by: org.apache.subversion.javahl.ClientException: svn: E204899: Cannot create new file 'TableNameMapping.java.tmp': Zugriff verweigert
	at org.apache.subversion.javahl.ClientException.fromException(ClientException.java:68)
	at org.tmatesoft.svn.core.javahl17.SVNClientImpl.getClientException(SVNClientImpl.java:1492)
	at org.tmatesoft.svn.core.javahl17.SVNClientImpl.diff(SVNClientImpl.java:1068)
	at org.tmatesoft.svn.core.javahl17.SVNClientImpl.diff(SVNClientImpl.java:969)
	at org.tigris.subversion.svnclientadapter.javahl.AbstractJhlClientAdapter.diff(AbstractJhlClientAdapter.java:2706)
	... 7 more
Caused by: org.tmatesoft.svn.core.SVNException: svn: E204899: Cannot create new file 'TableNameMapping.java.tmp': Zugriff verweigert
	at org.tmatesoft.svn.core.internal.wc.SVNErrorManager.error(SVNErrorManager.java:64)
	at org.tmatesoft.svn.core.internal.wc.SVNErrorManager.error(SVNErrorManager.java:51)
	at org.tmatesoft.svn.core.internal.io.svn.SVNEditModeReader.driveEditor(SVNEditModeReader.java:248)
	at org.tmatesoft.svn.core.internal.io.svn.SVNRepositoryImpl.diff(SVNRepositoryImpl.java:1440)
	at org.tmatesoft.svn.core.internal.wc2.ng.SvnNgDiff.doDiffReposWC(SvnNgDiff.java:358)
	at org.tmatesoft.svn.core.internal.wc2.ng.SvnNgDiff.doDiff(SvnNgDiff.java:115)
	at org.tmatesoft.svn.core.internal.wc2.ng.SvnNgDiff.run(SvnNgDiff.java:76)
	at org.tmatesoft.svn.core.internal.wc2.ng.SvnNgDiff.run(SvnNgDiff.java:32)
	at org.tmatesoft.svn.core.internal.wc2.ng.SvnNgOperationRunner.run(SvnNgOperationRunner.java:20)
	at org.tmatesoft.svn.core.internal.wc2.SvnOperationRunner.run(SvnOperationRunner.java:21)
	at org.tmatesoft.svn.core.wc2.SvnOperationFactory.run(SvnOperationFactory.java:1235)
	at org.tmatesoft.svn.core.wc2.SvnOperation.run(SvnOperation.java:294)
	at org.tmatesoft.svn.core.javahl17.SVNClientImpl.diff(SVNClientImpl.java:1064)
	... 9 more
```
