### ISSUE TITLE
NPE in ConfigurableMergeAction#selectionChanged

### ISSUE THREAD

**Issue by Gubbel** [subclipse/subclipse#77]
With subclipse 4.2.7 and eclipse 4.9 the following NPE occurs sporadically on text selections:

	java.lang.NullPointerException
		at org.tigris.subversion.subclipse.ui.internal.TeamAction.selectionChanged(TeamAction.java:256)
		at org.tigris.subversion.subclipse.ui.actions.ConfigurableMergeAction.selectionChanged(ConfigurableMergeAction.java:23)
		at org.eclipse.ui.internal.PluginAction.refreshEnablement(PluginAction.java:209)
		at org.eclipse.ui.internal.PluginAction.selectionChanged(PluginAction.java:276)
		at org.eclipse.ui.internal.PluginAction.selectionChanged(PluginAction.java:300)
		at org.eclipse.ui.internal.e4.compatibility.SelectionService.notifyListeners(SelectionService.java:242)

The exception is thrown because `getTargetPart().getSite().getPage()` returns null. The action's target part is a disposed editor. The PartSite of disposed parts no longer has a reference to its original workbench page (since eclipse 4.9, see [Bug 536677](https://bugs.eclipse.org/bugs/show_bug.cgi?id=536677)).

`ConfigurableMergeAction#setActivePart(IAction, IWorkbenchPart)` is apparently never called.

Full stacktrace: [stacktrace.log](https://github.com/subclipse/subclipse/files/2424147/stacktrace.log)

**Comment by Marco-Sulla** [comment]
I have [the same problems](https://bugs.eclipse.org/bugs/show_bug.cgi?id=547117). This is fixed in what version of Subclipse?

**Comment by Marco-Sulla** [comment]
Please, can you answer me? This bug bothers me a lot. I have Subclipse 4.3.0.201901172050 with Eclipse  20190314-1200, on ***L***ubuntu 18.04.2 64 bit. I'm using Java Azul Zulu 8.

**Comment by Marco-Sulla** [comment]
Hello?

**Comment by markphip** [comment]
The fix committed in this issue would be included in the 4.3.0 release.  Open a new issue with the new stack trace and if possible add a PR with the fix.

**Comment by Marco-Sulla** [comment]
And PR stands for...

**Comment by markphip** [comment]
PR stands for Pull Request
